export const constants = {
    HOME_HEADING: "Join the Movement for Social Justice",
    HOME_DESCRIPTION: "At AIISCA, we are committed to building a society where every individual, regardless of caste, has access to quality education and equal opportunities. Our initiatives, like the Savitribai Phule Resource Centre, provide safe spaces, resources, and mentorship to uplift marginalized communities.",
    WHO_WE_ARE: 'AIISCA is an autonomous Dalit movement organization founded on 16 July 2023 . We firmly believe in creating an independent cadre-based movement and nurturing leadership at both the grassroots and national levels. Taking into account the unique issues and problems faced by Dalit communities in different states, we are working towards establishing state-level bodies all over India.',
    WHAT_WE_DO: 'As an Autonomous Dalit Movement, we are driven by the goal of empowering and uplifting Dalit communities across regions and religions. We strive to challenge the deeply ingrained caste-based discriminations and inequalities that have persistently marginalized Dalits for generations. Our movement stands for the assertion of Dalit identity, dignity, and rights, while fostering unity and solidarity among Dalit individuals and communities.',
    MANIFESTO_HEADING: 'Together, we pledge to champion the rights of every individual, celebrate diversity, and work collectively toward a future where everyone has the opportunity to thrive. Let this be the foundation of a movement that transforms dreams of equity into a tangible, sustainable future for all.',
    MANIFESTO_DESCRIPTION2: 'We, the members of the All India Independent Scheduled Caste Association (AIISCA), stand united in our commitment to uphold the ideals of social justice, equality, and empowerment for Dalits across the nation. Recognizing the challenges faced by our community, we aim to build a strong and autonomous movement that advocates for the rights and well-being of Dalits in all spheres of life. With the legacy of Dr. B.R. Ambedkar as our guiding light, we pledge to work tirelessly towards transforming the current socio-economic landscape into one that reflects true democracy and inclusivity.',
    MANIFESTO_CONCLUSION: "The AIISCA Manifesto represents our collective commitment to ensuring that artificial intelligence serves as a force for good in human society. By adhering to these principles and frameworks, we can harness the transformative potential of AI while safeguarding our fundamental values",
   
    DEMANDS_DESCRIPTION:'Despite decades of independence, India remains far from Babasaheb’s vision of a true democracy. While upper-caste communities control institutions and resources, Dalits struggle for basic survival. The data on land ownership, income inequality, and lack of representation highlights this disparity.'

}